kowl:
  config:
    kafka:
      brokers:
        - # list of broker urls
        
      schemaRegistry:
        enabled: true
        urls:
          - # schema registry url
          
      tls:
        enabled: true
        
ingress:
  annotations:
    alb.ingress.kubernetes.io/tags: Stage=prod, App=Kowl
    alb.ingress.kubernetes.io/certificate-arn: # ACM certificate for https
    external-dns.stage.kubernetes.io/hostname: # External DNS hostname
  hosts:
    - host: # External DNS hostname
      paths: 
        - /*
